name: hello-world
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Define variable
              run: echo "USERNAME=${{github.actor}}" >> $GITHUB_ENV
            - uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'
            - run: npm install
            - run: node index.js